//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.13 at 01:38:45 PM EDT 
//


package edu.harvard.mcz.precapture.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Field complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Field">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VocabularyTerm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Optional" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="UseItalic" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="NewLine" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="FontSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Field", propOrder = {
    "label",
    "code",
    "type",
    "vocabularyTerm",
    "optional",
    "useItalic",
    "newLine",
    "fontSize"
})
public class Field {

    @XmlElement(name = "Label", required = true)
    protected String label;
    @XmlElement(name = "Code", required = true)
    protected String code;
    @XmlElement(name = "Type", required = true)
    protected String type;
    @XmlElement(name = "VocabularyTerm", required = true)
    protected String vocabularyTerm;
    @XmlElement(name = "Optional")
    protected boolean optional;
    @XmlElement(name = "UseItalic")
    protected boolean useItalic;
    @XmlElement(name = "NewLine")
    protected boolean newLine;
    @XmlElement(name = "FontSize")
    protected int fontSize;

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the vocabularyTerm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVocabularyTerm() {
        return vocabularyTerm;
    }

    /**
     * Sets the value of the vocabularyTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVocabularyTerm(String value) {
        this.vocabularyTerm = value;
    }

    /**
     * Gets the value of the optional property.
     * 
     */
    public boolean isOptional() {
        return optional;
    }

    /**
     * Sets the value of the optional property.
     * 
     */
    public void setOptional(boolean value) {
        this.optional = value;
    }

	/**
	 * @return the useItalic
	 */
	public boolean isUseItalic() {
		return useItalic;
	}

	/**
	 * @param useItalic the useItalic to set
	 */
	public void setUseItalic(boolean useItalic) {
		this.useItalic = useItalic;
	}

	/**
	 * @return the newLine
	 */
	public boolean isNewLine() {
		return newLine;
	}

	/**
	 * @param newLine the newLine to set
	 */
	public void setNewLine(boolean newLine) {
		this.newLine = newLine;
	}

	/**
	 * @return the fontSize
	 */
	public int getFontSize() {
		return fontSize;
	}

	/**
	 * @param fontSize the fontSize to set
	 */
	public void setFontSize(int fontSize) {
		this.fontSize = fontSize;
	}

    
}
