//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.01 at 06:10:51 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://mcz.harvard.edu/PreCaptureFieldSchema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package edu.harvard.mcz.precapture.xml;
