//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.13 at 01:38:45 PM EDT 
//


package edu.harvard.mcz.imagecapture.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.harvard.mcz.imagecapture.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FieldMapping_QNAME = new QName("http://www.example.org/PreCaptureFieldSchema", "FieldMapping");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.harvard.mcz.imagecapture.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MappingList }
     * 
     */
    public MappingList createMappingList() {
        return new MappingList();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MappingList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/PreCaptureFieldSchema", name = "FieldMapping")
    public JAXBElement<MappingList> createFieldMapping(MappingList value) {
        return new JAXBElement<MappingList>(_FieldMapping_QNAME, MappingList.class, null, value);
    }

}
