//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.25 at 08:32:56 AM EDT 
//


package edu.harvard.mcz.precapture.xml.labels;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LabelDefinitionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LabelDefinitionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Units" type="{http://mcz.harvard.edu/LabelDefinitionSchema}UnitsType"/>
 *         &lt;element name="PaperHeight" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="PaperWidth" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="Margins" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="Columns" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="LabelWidth" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="LabelHeight" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="TextOrentation" type="{http://mcz.harvard.edu/LabelDefinitionSchema}TextOrentationType"/>
 *         &lt;element name="FontDelta" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LabelDefinitionType", propOrder = {
    "title",
    "units",
    "paperHeight",
    "paperWidth",
    "margins",
    "columns",
    "labelWidth",
    "labelHeight",
    "textOrentation",
    "fontDelta"
})
public class LabelDefinitionType {

    @XmlElement(name = "Title", required = true)
    protected String title;
    @XmlElement(name = "Units", required = true)
    protected UnitsType units;
    @XmlElement(name = "PaperHeight")
    protected float paperHeight;
    @XmlElement(name = "PaperWidth")
    protected float paperWidth;
    @XmlElement(name = "Margins")
    protected float margins;
    @XmlElement(name = "Columns")
    protected int columns;
    @XmlElement(name = "LabelWidth")
    protected float labelWidth;
    @XmlElement(name = "LabelHeight")
    protected float labelHeight;
    @XmlElement(name = "TextOrentation", required = true)
    protected TextOrentationType textOrentation;
    @XmlElement(name = "FontDelta")
    protected float fontDelta = 0f;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link UnitsType }
     *     
     */
    public UnitsType getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitsType }
     *     
     */
    public void setUnits(UnitsType value) {
        this.units = value;
    }

    /**
     * Gets the value of the paperHeight property.
     * 
     */
    public float getPaperHeight() {
        return paperHeight;
    }

    /**
     * Sets the value of the paperHeight property.
     * 
     */
    public void setPaperHeight(float value) {
        this.paperHeight = value;
    }

    /**
     * Gets the value of the paperWidth property.
     * 
     */
    public float getPaperWidth() {
        return paperWidth;
    }

    /**
     * Sets the value of the paperWidth property.
     * 
     */
    public void setPaperWidth(float value) {
        this.paperWidth = value;
    }

    /**
     * Gets the value of the margins property.
     * 
     */
    public float getMargins() {
        return margins;
    }

    /**
     * Sets the value of the margins property.
     * 
     */
    public void setMargins(float value) {
        this.margins = value;
    }

    /**
     * Gets the value of the columns property.
     * 
     */
    public int getColumns() {
        return columns;
    }

    /**
     * Sets the value of the columns property.
     * 
     */
    public void setColumns(int value) {
        this.columns = value;
    }

    /**
     * Gets the value of the labelWidth property.
     * 
     */
    public float getLabelWidth() {
        return labelWidth;
    }

    /**
     * Sets the value of the labelWidth property.
     * 
     */
    public void setLabelWidth(float value) {
        this.labelWidth = value;
    }

    /**
     * Gets the value of the labelHeight property.
     * 
     */
    public float getLabelHeight() {
        return labelHeight;
    }

    /**
     * Sets the value of the labelHeight property.
     * 
     */
    public void setLabelHeight(float value) {
        this.labelHeight = value;
    }

    /**
     * Gets the value of the textOrentation property.
     * 
     * @return
     *     possible object is
     *     {@link TextOrentationType }
     *     
     */
    public TextOrentationType getTextOrentation() {
        return textOrentation;
    }

    /**
     * Sets the value of the textOrentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextOrentationType }
     *     
     */
    public void setTextOrentation(TextOrentationType value) {
        this.textOrentation = value;
    }

	/**
	 * @return the fontDelta
	 */
	public float getFontDelta() {
		return fontDelta;
	}

	/**
	 * @param fontDelta the fontDelta to set
	 */
	public void setFontDelta(float fontDelta) {
		this.fontDelta = fontDelta;
	}

}
