//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.25 at 08:32:56 AM EDT 
//


package edu.harvard.mcz.precapture.xml.labels;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LabelDefinitionListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LabelDefinitionListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LabelDefinition" type="{http://mcz.harvard.edu/LabelDefinitionSchema}LabelDefinitionType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="LabelDefinitions")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LabelDefinitionListType", propOrder = {
    "labelDefinition"
})
public class LabelDefinitionListType {

    @XmlElement(name = "LabelDefinition", required = true)
    protected List<LabelDefinitionType> labelDefinition;

    /**
     * Gets the value of the labelDefinition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the labelDefinition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLabelDefinition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LabelDefinitionType }
     * 
     * 
     */
    public List<LabelDefinitionType> getLabelDefinition() {
        if (labelDefinition == null) {
            labelDefinition = new ArrayList<LabelDefinitionType>();
        }
        return this.labelDefinition;
    }

}
