//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.25 at 08:32:56 AM EDT 
//


package edu.harvard.mcz.precapture.xml.labels;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.harvard.mcz.precapture.xml.labels package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LabelDefinitions_QNAME = new QName("http://mcz.harvard.edu/LabelDefinitionSchema", "LabelDefinitions");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.harvard.mcz.precapture.xml.labels
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LabelDefinitionListType }
     * 
     */
    public LabelDefinitionListType createLabelDefinitionListType() {
        return new LabelDefinitionListType();
    }

    /**
     * Create an instance of {@link LabelDefinitionType }
     * 
     */
    public LabelDefinitionType createLabelDefinitionType() {
        return new LabelDefinitionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LabelDefinitionListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mcz.harvard.edu/LabelDefinitionSchema", name = "LabelDefinitions")
    public JAXBElement<LabelDefinitionListType> createLabelDefinitions(LabelDefinitionListType value) {
        return new JAXBElement<LabelDefinitionListType>(_LabelDefinitions_QNAME, LabelDefinitionListType.class, null, value);
    }

}
