//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.25 at 08:32:56 AM EDT 
//


package edu.harvard.mcz.precapture.xml.labels;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TextOrentationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TextOrentationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Horizontal"/>
 *     &lt;enumeration value="Vertical"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TextOrentationType")
@XmlEnum
public enum TextOrentationType {

    @XmlEnumValue("Horizontal")
    HORIZONTAL("Horizontal"),
    @XmlEnumValue("Vertical")
    VERTICAL("Vertical");
    private final String value;

    TextOrentationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TextOrentationType fromValue(String v) {
        for (TextOrentationType c: TextOrentationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
